package cn.kgc.crowd.mapper;


import cn.kgc.crowd.entity.Pl;
import cn.kgc.crowd.entity.PlExample;
import org.apache.ibatis.annotations.Param;

import java.awt.print.Book;
import java.util.List;
import java.util.Map;

public interface PlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:12 CST 2020
     */
    long countByExample(PlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:12 CST 2020
     */
    int deleteByExample(PlExample example);
    List<Map<String,Object>>queryAllPage(Integer pNo, Integer pSize);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:12 CST 2020
     */
    int insert(Pl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:12 CST 2020
     */
    int insertSelective(Pl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:13 CST 2020
     */
    List<Pl> selectByExample(PlExample example);
    List<Pl> selectByxiaoshuoid(@Param("xiaoshuoid") int xiaoshuoid) ;
    List<Pl> selectByuserid(@Param("userid") int userid) ;
    List<Pl> selectA();
    Integer delete(@Param("id") Integer id);
    Integer addPl(@Param("pl") Pl pl);
    Integer updataPl(@Param("pl") Pl pl);
    //查询一个
    Pl getOne(@Param("id") Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:13 CST 2020
     */
    Pl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Pl record, @Param("example") PlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:13 CST 2020
     */
    int updateByExample(@Param("record") Pl record, @Param("example") PlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:13 CST 2020
     */
    int updateByPrimaryKeySelective(Pl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl
     *
     * @mbg.generated Fri Aug 07 21:29:13 CST 2020
     */
    int updateByPrimaryKey(Pl record);
}